services:
  db:
    image: postgres:16
    container_name: desafio3-db
    environment:
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: teste
    volumes:
      - dbdata_desafio3:/var/lib/postgresql/data

  cache:
    image: redis:7
    container_name: desafio3-cache

  web:
    build: ./web
    container_name: desafio3-web
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: senha123
      DB_NAME: teste
      REDIS_HOST: cache
    depends_on:
      - db
      - cache
    ports:
      - "3000:3000"

volumes:
  dbdata_desafio3:
